[2025-02-19T19:14:04.442+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T19:14:04.449+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yfinance.fetch_and_store_apple_stock_data scheduled__2025-02-19T19:13:00+00:00 [queued]>
[2025-02-19T19:14:04.452+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yfinance.fetch_and_store_apple_stock_data scheduled__2025-02-19T19:13:00+00:00 [queued]>
[2025-02-19T19:14:04.452+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-19T19:14:04.456+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): fetch_and_store_apple_stock_data> on 2025-02-19 19:13:00+00:00
[2025-02-19T19:14:04.460+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=13723) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-19T19:14:04.461+0000] {standard_task_runner.py:72} INFO - Started process 13724 to run task
[2025-02-19T19:14:04.461+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_yfinance', 'fetch_and_store_apple_stock_data', 'scheduled__2025-02-19T19:13:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/DAG1.py', '--cfg-path', '/tmp/tmp4hftcuzk']
[2025-02-19T19:14:04.461+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask fetch_and_store_apple_stock_data
[2025-02-19T19:14:04.482+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_yfinance.fetch_and_store_apple_stock_data scheduled__2025-02-19T19:13:00+00:00 [running]> on host 07747019ad3d
[2025-02-19T19:14:04.512+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_yfinance' AIRFLOW_CTX_TASK_ID='fetch_and_store_apple_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T19:13:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T19:13:00+00:00'
[2025-02-19T19:14:04.513+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-19T19:14:04.513+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-19T19:14:04.513+0000] {logging_mixin.py:190} INFO - Current task name:fetch_and_store_apple_stock_data state:running start_date:2025-02-19 19:14:04.449656+00:00
[2025-02-19T19:14:04.513+0000] {logging_mixin.py:190} INFO - Dag name:dag_yfinance and current dag run status:running
[2025-02-19T19:14:04.513+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-19T19:14:04.513+0000] {sql.py:295} INFO - Executing: 
            insert into stock_data (dt, stock_symbol, open_price, close_price) 
            values ('2025-02-19T19:13:00+00:00', 'AAPL', 'None', 'None')
        
[2025-02-19T19:14:04.516+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-02-19T19:14:04.519+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-02-19T19:14:04.523+0000] {sql.py:511} INFO - Running statement: 
            insert into stock_data (dt, stock_symbol, open_price, close_price) 
            values ('2025-02-19T19:13:00+00:00', 'AAPL', 'None', 'None')
        , parameters: None
[2025-02-19T19:14:04.525+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "None"
LINE 3: ...     values ('2025-02-19T19:13:00+00:00', 'AAPL', 'None', 'N...
                                                             ^

[2025-02-19T19:14:04.529+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-19T19:14:04.530+0000] {logging_mixin.py:190} INFO - Task start:2025-02-19 19:14:04.449656+00:00 end:2025-02-19 19:14:04.529787+00:00 duration:0.080131
[2025-02-19T19:14:04.530+0000] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): fetch_and_store_apple_stock_data> dag:<DAG: dag_yfinance> dagrun:<DagRun dag_yfinance @ 2025-02-19 19:13:00+00:00: scheduled__2025-02-19T19:13:00+00:00, state:running, queued_at: 2025-02-19 19:14:00.732265+00:00. externally triggered: False>
[2025-02-19T19:14:04.530+0000] {logging_mixin.py:190} INFO - Failure caused by invalid input syntax for type double precision: "None"
LINE 3: ...     values ('2025-02-19T19:13:00+00:00', 'AAPL', 'None', 'N...
                                                             ^
[2025-02-19T19:14:04.530+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_yfinance, task_id=fetch_and_store_apple_stock_data, run_id=scheduled__2025-02-19T19:13:00+00:00, execution_date=20250219T191300, start_date=20250219T191404, end_date=20250219T191404
[2025-02-19T19:14:04.539+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-19T19:14:04.539+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 78 for task fetch_and_store_apple_stock_data (invalid input syntax for type double precision: "None"
LINE 3: ...     values ('2025-02-19T19:13:00+00:00', 'AAPL', 'None', 'N...
                                                             ^
; 13724)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "None"
LINE 3: ...     values ('2025-02-19T19:13:00+00:00', 'AAPL', 'None', 'N...
                                                             ^

[2025-02-19T19:14:04.559+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-19T19:14:04.568+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-19T19:14:04.568+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-19T19:14:36.807+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T19:14:36.813+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yfinance.fetch_and_store_apple_stock_data scheduled__2025-02-19T19:13:00+00:00 [queued]>
[2025-02-19T19:14:36.817+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yfinance.fetch_and_store_apple_stock_data scheduled__2025-02-19T19:13:00+00:00 [queued]>
[2025-02-19T19:14:36.817+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-19T19:14:36.821+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): fetch_and_store_apple_stock_data> on 2025-02-19 19:13:00+00:00
[2025-02-19T19:14:36.825+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=14043) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-19T19:14:36.826+0000] {standard_task_runner.py:72} INFO - Started process 14044 to run task
[2025-02-19T19:14:36.826+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_yfinance', 'fetch_and_store_apple_stock_data', 'scheduled__2025-02-19T19:13:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/DAG1.py', '--cfg-path', '/tmp/tmpntxvf9ea']
[2025-02-19T19:14:36.826+0000] {standard_task_runner.py:105} INFO - Job 86: Subtask fetch_and_store_apple_stock_data
[2025-02-19T19:14:36.851+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_yfinance.fetch_and_store_apple_stock_data scheduled__2025-02-19T19:13:00+00:00 [running]> on host 07747019ad3d
[2025-02-19T19:14:36.884+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_yfinance' AIRFLOW_CTX_TASK_ID='fetch_and_store_apple_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T19:13:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T19:13:00+00:00'
[2025-02-19T19:14:36.885+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-19T19:14:36.885+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-19T19:14:36.885+0000] {logging_mixin.py:190} INFO - Current task name:fetch_and_store_apple_stock_data state:running start_date:2025-02-19 19:14:36.814095+00:00
[2025-02-19T19:14:36.885+0000] {logging_mixin.py:190} INFO - Dag name:dag_yfinance and current dag run status:running
[2025-02-19T19:14:36.885+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-19T19:14:36.885+0000] {sql.py:295} INFO - Executing: 
            insert into stock_data (dt, stock_symbol, open_price, close_price) 
            values ('2025-02-19T19:13:00+00:00', 'AAPL', '244.77999877929688', '244.77999877929688')
        
[2025-02-19T19:14:36.888+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-02-19T19:14:36.891+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-02-19T19:14:36.895+0000] {sql.py:511} INFO - Running statement: 
            insert into stock_data (dt, stock_symbol, open_price, close_price) 
            values ('2025-02-19T19:13:00+00:00', 'AAPL', '244.77999877929688', '244.77999877929688')
        , parameters: None
[2025-02-19T19:14:36.896+0000] {sql.py:520} INFO - Rows affected: 1
[2025-02-19T19:14:36.897+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:470 DeprecationWarning: Import of fetch_all_handler from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
[2025-02-19T19:14:36.897+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:471 DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
[2025-02-19T19:14:36.899+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:486 DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
[2025-02-19T19:14:36.899+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/operators/sql.py:311 DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
[2025-02-19T19:14:36.902+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-19T19:14:36.902+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_yfinance, task_id=fetch_and_store_apple_stock_data, run_id=scheduled__2025-02-19T19:13:00+00:00, execution_date=20250219T191300, start_date=20250219T191436, end_date=20250219T191436
[2025-02-19T19:14:36.908+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-19T19:14:36.908+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-19T19:14:36.909+0000] {logging_mixin.py:190} INFO - Dag name:dag_yfinance queued_at:2025-02-19 19:14:32.903546+00:00
[2025-02-19T19:14:36.909+0000] {logging_mixin.py:190} INFO - Task hostname:07747019ad3d operator:SQLExecuteQueryOperator
[2025-02-19T19:14:36.924+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-19T19:14:36.930+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-19T19:14:36.930+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
